version: '2'
services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - env
    links:
      - db
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - "3306:3306"
    env_file:
      - env
    volumes:
      - ../../../../_local_mysql_data:/var/lib/mysql